server {
	listen 8080;
	server_name localhost;				# 域名，ip地址，或者通配符（*）都可以，localhost是本机地址
	client_max_body_size 10M;

	error_page 400 www/errors/400.html; # Bad Request
	error_page 403 www/errors/403.html; # Forbidden
	error_page 404 www/errors/404.html; # CHECK Not Found
	error_page 405 www/errors/405.html; # Method Not Allowed
	error_page 413 www/errors/413.html; # Payload Too Large
	error_page 500 www/errors/500.html; # Internal Server Error

	# Default location 
	location / {
		root www;
		index index.html;
		methods GET POST;
		autoindex on;
	}

	# Upload location
	location /upload {
		root www/upload;
		methods GET POST DELETE;
		autoindex on;
		upload_path www/upload;
	}

	# CGI location
	location /cgi-bin {
		root cgi-bin;
		methods GET POST;

		cgi_ext .py;
		cgi_path /usr/bin/python3;

		autoindex off;
	}

	location /cgi-sh {
		root cgi-bin;
		methods GET POST;
		cgi_ext .sh;
		cgi_path /usr/bin/bash;
	}

	location /cgi-pl {
		root cgi-bin;
		methods GET POST;
		cgi_ext .pl;
		cgi_path /usr/bin/perl;
	}

	# Directory listing demo
	location /files {
		root www;
		methods GET;
		autoindex on;
	}

	# Redirect demo
	location /old-page {
	# 301 Moved Permanently
	# return <status_code> <url>; 
		return 301 /;
	}
}

# multi-port listening
server {
	listen 8081;
	server_name localhost;
	client_max_body_size 1M; #客户端一次请求允许上传的最大数据体（body）大小
	
	location / {
		root www;
		index index8081.html;
		methods GET;
		autoindex off;
	}
}