server {
	listen 8080;
	server_name localhost;
	client_max_body_size 10M; #客户端一次请求允许上传的最大数据体（body）大小

	error_page 400 www/errors/400.html; # Bad Request 请求格式错误，服务器根本看不懂
	error_page 403 www/errors/403.html; # Forbidden 服务器知道资源存在，但拒绝访问
	error_page 404 www/errors/404.html; # CHECK Not Found 路径不存在
	error_page 405 www/errors/405.html; # Method Not Allowed URL存在，但 HTTP method 不允许
	error_page 413 www/errors/413.html; # Payload Too Large 上传数据太大
	error_page 500 www/errors/500.html; # Internal Server Error 服务器自己崩了/出错了

	# Default location 
	# 兜底规则（fallback）：如果没有更具体的 location，就用它。
	location / {
		# 这个URL对应磁盘上的哪个目录：root + URL path
		root www;
		# 如果访问的是directory目录，就在默认在这个目录里找这个文件
		index index.html;
		# 允许哪些 HTTP 方法
		methods GET POST DELETE;
		# 如果没有index.html这个文件，不自动生成index页面，返回403
		autoindex off;
	}

	# Upload location
	location /upload {
		root www; #❗root www/load错误
		methods GET POST DELETE;
		autoindex off;
		upload_path www/upload;
	}

	# CGI location
	location /cgi-bin {
		root .; #❗当前目录
		# 直接运行多个脚本
		methods GET POST;

		cgi_ext .py;
		cgi_path /usr/bin/python3;

		autoindex off;

		# cgi_ext .sh;
		# cgi_path /usr/bin/bash;

		# cgi_ext .pl;
		# cgi_path /usr/bin/perl;

	}

	# Redirect demo 之前的网址搬家
	location /old-page {
	# 301 Moved Permanently
	# return <status_code> <url>; 301是状态码 /是主页
		return 301 /;
	}

	# Directory listing demo 做测试用
	location /files {
		root www;
		methods GET;
		autoindex on;
	}
}

# multi-port listening
server {
	listen 8081;
	server_name localhost;
	client_max_body_size 10M; #客户端一次请求允许上传的最大数据体（body）大小
	
	location / {
	root www;
	index index.html;
	methods GET;
	autoindex off;
	}
}