server {
	listen 8080;						# http://localhost:8080 通过8080端口访问这个server
	server_name localhost;				# 域名，ip地址，或者通配符（*）都可以，localhost是本机地址
	client_max_body_size 10M; 			# 客户端一次请求允许上传的最大数据体（body）大小

	error_page 400 www/errors/400.html; # Bad Request 客户端请求格式错误(e.g. GE T / HTTP/1.1)，服务器看不懂
	error_page 403 www/errors/403.html; # Forbidden 服务器知道资源存在，但拒绝访问
	error_page 404 www/errors/404.html; # CHECK Not Found 路径不存在
	error_page 405 www/errors/405.html; # Method Not Allowed URL存在，但HTTP method不允许(PUT, PATCH, HEAD...除了GET, POST, DELETE外的其他方法)
	error_page 413 www/errors/413.html; # Payload Too Large 上传数据太大
	error_page 500 www/errors/500.html; # Internal Server Error 服务器自己崩了/出错了

	# Default location 
	# 兜底规则（fallback）：如果没有更具体的 location，就用它。
	location / {
		# 这个URL对应磁盘上的哪个目录：root + URL path
		root www;
		# 如果访问的是directory目录，就在默认在这个目录里找这个文件
		index index.html;
		# 允许哪些 HTTP 方法（读取资源，提交数据，删除资源）
		methods GET;
		# 如果没有index.html这个文件，不自动生成index页面，返回403
		autoindex on;
	}

	# Upload location
	location /upload {
		root www/upload;
		methods GET POST DELETE;
		autoindex on;
		upload_path www/upload;
	}

	# CGI location
	location /cgi-bin {
		root cgi-bin;
		# 直接运行多个脚本
		methods GET POST;

		cgi_ext .py;
		cgi_path /usr/bin/python3;

		autoindex off;
	}

	location /cgi-sh {
		root cgi-bin;
		methods GET POST;
		cgi_ext .sh;
		cgi_path /usr/bin/bash;
	}

	location /cgi-pl {
		root cgi-bin;
		methods GET POST;
		cgi_ext .pl;
		cgi_path /usr/bin/perl;
	}

	# Directory listing demo 做测试用
	location /files {
		root www;
		methods GET;
		autoindex on;
	}

	# Redirect demo 之前的网址搬家
	location /old-page {
	# 301 Moved Permanently
	# return <status_code> <url>; 301是状态码 /是主页
		return 301 /;
	}
}

# multi-port listening
server {
	listen 8081;
	server_name localhost;
	client_max_body_size 10M; #客户端一次请求允许上传的最大数据体（body）大小
	
	location / {
		root www;
		index index8081.html;
		methods GET;
		autoindex off;
	}
}