server {
    listen 8080;
    server_name localhost;

    location / {
        root YoupiBanane;
        methods GET;
        index index.html;
        autoindex on;
    }

    location /post_body {
        root www;
        methods POST;
        client_max_body_size 100;
		upload_path www/upload;
    }

    location /directory/ {
        root YoupiBanane;
        methods GET POST;
        index youpi.bad_extension;
        autoindex off;
        client_max_body_size 100000000;

        cgi_ext .bla;
        cgi_path YoupiBanane/cgi_tester;
    }
}