server {
    listen 8080;
    server_name localhost;

    location / {
        root YoupiBanane;
        methods GET;
        index index.html;
        autoindex on;
    }

    location /post_body {
        root www;
        methods POST;
        client_max_body_size 100;
        upload_path www/upload;
    }

    # location *.bla {
    #     methods POST;
    #     root YoupiBanane;
    #     cgi_path ./cgi_tester;
    #     client_max_body_size 200000000;
    # }

    location /directory/ {
        root YoupiBanane;
        methods GET POST;
        index youpi.bad_extension;
        autoindex off;
        client_max_body_size 100000000;

        cgi_ext .bla;
        cgi_path YoupiBanane/cgi_tester;
    }
}

# HEAD

# REQUEST：
# HEAD /index.html HTTP/1.1
# Host: localhost

# RESPONSE：
# HTTP/1.1 200 OK
# Content-Type: text/html
# Content-Length: 49
# Last-Modified: Wed, 21 Oct 2015 07:28:00 GMT