server {
    listen 8080;
    server_name localhost;
    client_max_body_size 100; 

    location / {
        root www;
        methods GET;
        index index.html;
    }

    location /post_body {
        root www;
        methods POST;
    }

    location /cgi-bin {
        root cgi-bin;
        methods POST;
        cgi_ext .bla;
        cgi_path ./cgi-bin/cgi_test;
    }

    location /directory {
        root YoupiBanane;
        methods GET;
        index youpi.bad_extension;
        autoindex off;
    }
}

# HEAD

# REQUEST：
# HEAD /index.html HTTP/1.1
# Host: localhost

# RESPONSE：
# HTTP/1.1 200 OK
# Content-Type: text/html
# Content-Length: 49
# Last-Modified: Wed, 21 Oct 2015 07:28:00 GMT