#!/usr/bin/env python3
import os

print("Content-Type: text/html")
print()
print("<!DOCTYPE html>")
print("<html><head><title>Hello CGI</title></head>")
print("<body>")
print("<h1>Hello from CGI!</h1>")
print("<p>This page was generated by a Python CGI script.</p>")
print("<p>Request Method: {}</p>".format(os.environ.get("REQUEST_METHOD", "unknown")))
print("<p>Query String: {}</p>".format(os.environ.get("QUERY_STRING", "")))
print("<p><a href='/'>Back to home</a></p>")
print("</body></html>")
