#!/usr/bin/perl

print "Content-Type: text/html\r\n";
print "\r\n";
print "<!DOCTYPE html>\n";
print "<html><head><title>Perl CGI</title></head>\n";
print "<body>\n";
print "<h1>Hello from Perl CGI!</h1>\n";
print "<p>This page was generated by a Perl script.</p>\n";
print "<p>Request Method: $ENV{'REQUEST_METHOD'}</p>\n";
print "<p>Query String: $ENV{'QUERY_STRING'}</p>\n";
print "<p>Server Software: $ENV{'SERVER_SOFTWARE'}</p>\n";
print "<p><a href='/'>Back to home</a></p>\n";
print "</body></html>\n";
